name: design_system
description: Design System - IATEC.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:  
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Montserrat-Medium.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Roboto-Medium.ttf
          weight: 500
    - family:  DSIcons
      fonts:
       - asset: lib/assets/fonts/DSIcons.ttf
    - family: DSNumberIcons
      fonts:
       - asset: lib/assets/fonts/DSNumberIcons.ttf